name: Rails RSpec Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.5', '2.6', '2.7', '3.0', '3.1', '3.2']

    # services:
    #   postgres:
    #     image: postgres:13
    #     ports:
    #       - 5432:5432
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_DB: test

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Ruby with a specific version
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # Automatically installs and caches gems

    # Step 3: Install Rails dependencies
    - name: Install dependencies
      run: |
        bundle install

    # Step 4: Set up the database
    - name: Set up Database
      run: |
        cp config/database.yml.ci config/database.yml # Ensure your CI config is properly set up
        bundle exec rails db:create db:migrate

    # Step 5: Run RSpec tests
    - name: Run RSpec tests
      run: bundle exec rspec
